# Generated by Django 3.0.8 on 2022-03-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="created_by",
        ),
    ]
