# Generated by Django 3.0.8 on 2022-03-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_auto_20220308_1825"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="created_by",
        ),
    ]
