# Generated by Django 3.0.8 on 2022-03-09 00:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_remove_menuitem_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_items",
                to="menu.Menu",
            ),
        ),
    ]
