# Generated by Django 3.0.8 on 2022-03-09 00:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_auto_20220309_0020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
